# Generated by Django 3.0.5 on 2020-04-23 23:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0002_auto_20200423_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='should_know',
            field=models.CharField(default='N/A', max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
