# Generated by Django 3.0.5 on 2020-04-23 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20200423_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='should_know',
            field=models.CharField(max_length=500),
        ),
    ]
