# Generated by Django 3.0.5 on 2020-04-24 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_post_post_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_date',
            new_name='pub_date',
        ),
    ]
