# Generated by Django 3.0.5 on 2020-05-01 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_auto_20200429_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewers',
            name='slug',
            field=models.SlugField(default='agwebberley', max_length=255, unique=True),
        ),
    ]
