# Generated by Django 3.0.5 on 2020-05-01 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_auto_20200501_1100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewers',
            old_name='slug',
            new_name='slugr',
        ),
    ]
