# Generated by Django 3.0.5 on 2020-05-01 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_auto_20200501_1101'),
    ]

    operations = [
        migrations.DeleteModel(
            name='reviewers',
        ),
    ]
