# Generated by Django 3.0.5 on 2020-05-01 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewerspages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewer',
            old_name='slugr',
            new_name='slug',
        ),
    ]
